apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: percona
  labels:
    name: percona
spec:
  replicas: 1
  selector:
    matchLabels:
      name: percona
  template:
    metadata:
      labels:
        name: percona
    spec:
      securityContext:
        fsGroup: 999
      tolerations:
      - key: "ak"
        value: "av"
        operator: "Equal"
        effect: "NoSchedule"
      containers:
      - name: percona
        image: percona
        args:
        - "--ignore-db-dir"
        - "lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: k8sDem0
        ports:
        - containerPort: 3306
          name: percona
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: demo-vol1
      volumes:
      - name: demo-vol1
        persistentVolumeClaim:
          claimName: openebs-pvc