@startuml
 
start

if (Kubernetes.version == v1.10) then (true)
    fork
    repeat
        while (visit each new StorageClass) is (true)
            if (sc.provisioner == kubernetes.io/rbd) then (true)
                if (kube-system namespace contains Ceph secret) then (true)
                    while (visit each namespace name) is (true)
                        if (namespace != kube-system) then (true)
                            :Create/update secret in current namespace;
                        else (false)
                        endif
                    endwhile (false)
                else (false)
                endif
            else (false)
            endif
        endwhile (false)
    repeat while (true) is (true)
    fork again
    repeat
        while (visit each new namespace) is (true)
            while (visit each StorageClass) is(true)
                if (sc.provisioner == kubernetes.io/rbd) then (true)
                    if (kube-system namespace contains Ceph secret) then (true)
                        :Create/update secret in new namespace;
                    else (false)
                    endif
                else (false)
                endif
            endwhile (false)
        endwhile (false)
    repeat while (true) is (true)
    end fork
else (false)
stop
endif
stop
@enduml


